pipeline{ 
    agent any
    environment {
        PATH = "$PATH:/usr/share/maven/apache-maven-3.0.5/bin"
    }
    stages{
        stage('git'){
            steps{
                git branch: 'master', credentialsId: 'git', url: 'https://github.com/swetha2310/hello-world.git'
            }
        }
	    stage('Build'){
            steps{
                sh 'mvn clean package'
            }
         }
        stage('SonarQube analysis'){
//    def scannerHome = tool 'SonarScanner 4.0';
            steps{
                withSonarQubeEnv('sonarqube8.9.10') { 
                // If you have configured more than one global server connection, you can specify its name
//              sh "${scannerHome}/bin/sonar-scanner"
                sh "mvn sonar:sonar"
                }
            }
      	 }
     }
 }
